import Head from 'next/head';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Homepage from '../component/Home/Home';
import '@fortawesome/fontawesome-svg-core/styles.css'


function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage datahome={data} />
    </>
  )

}

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:5000/getdata/`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default Home;
